import type { Metadata } from 'next'
import './globals.css'
import { DarkWrapper, } from './contexts/darktheme'
import { Authprovider } from './contexts/AuthContext'

export const metadata: Metadata = {
  title: 'Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
        <body className={`font-arial`}>
        <Authprovider>
          <DarkWrapper>
            {children}
          </DarkWrapper>
        </Authprovider>
          </body>
      </html>
  )
}
